### ISSUE TITLE
Trying out the implicit filtering method 

### ISSUE THREAD

**Issue by niyi4oau** [lasiadhi/USACE-Bathymetry#112]
I am playing with the implicit filtering method. The result still not good.

**Comment by lasiadhi** [comment]
cool! I am also playing with it. Mine is also not good. Change the objective function to fv =  norm(k_appro - k_noisy)^2 +  1e-8 \* norm(h)^2;

Then tune the reg. parameter (here 1e-8) and see what happen.

**Comment by lasiadhi** [comment]
No need to set the least squares option on when you call the method with the above fv.
