### ISSUE TITLE
wave height plot(H&index) in forward file

### ISSUE THREAD

**Issue by montymudra** [lasiadhi/USACE-Bathymetry#126]
The modified forward model seems not giving the correct plot for wave height.

**Comment by montymudra** [comment]
In code->forward->
realdata_H_modified.m
waveheight_H_modified.m
plot is in png file as H&index

**Comment by thesser1** [comment]
Why is there a rho_g/8 in the equation on line 64?  It makes you divide
the dissipation value by an extra 1/8_rho*g in the solution for H.

**Comment by thesser1** [comment]
Sorry, I don't have access to fsolve in my matlab so I cannot test this on my computer.  Let me know if it worked.

**Comment by montymudra** [comment]
that c is just the constant for finite difference steps. @dwb1988  will update the file writing the coefficient. cc is celerity in that code.

**Comment by montymudra** [comment]
file is pushed.

**Comment by dwb1988** [comment]
changed 'c' to 'coe'
tried two ways to get celerity as 'cc' (2_pi/(k(i)_Tb))& 'cc1' (sqrt(g*h(i))), slightly difference showed
not sure how to deal with the part where depth down to zero (just forced 'H' to zero)
the eqn gives NaN for H around i=106 but h is not that small (0.0025).

**Comment by thesser1** [comment]
Just made a push, please try again.   I think the problem was on my teaching so I apologize with regards to the Hrms but also make sure you are not dividing by a constant that does not match the equation.

**Comment by dwb1988** [comment]
It works and the trend changes a little (still not look like in a good shape)

plot in 'forward' file as those 'png's

**Comment by thesser1** [comment]
I think the images look like solutions for the bathymetry and the wave
characteristics you are running.   Go with it.
