### ISSUE TITLE
Generating RMSE for all reconstructions

### ISSUE THREAD

**Issue by lasiadhi** [lasiadhi/USACE-Bathymetry#138]
Find the fmincon synthatic reconstruction at IMSM_workshop_2016/Project/USACE-Bathymetry/Code/Inverse_problem/Least_square/Results_fmincon/final_plots/h_hat_synthatic_25m_fmincon_plot23-modified.mat

**Comment by lasiadhi** [comment]
pushed!

**Comment by Nellz91** [comment]
Thanks!

**Comment by lasiadhi** [comment]
Try to read h values in the area of sand bar using the command:
sandBar_h = h_hat(xq>600 & xq<1150)

**Comment by lasiadhi** [comment]
Try this: sandBar_h = h_hat(xq>=600 & xq=<1150)
