### ISSUE TITLE
Extract data for NRMSE MCMC (Sandbar & Entire 1D Tract)

### ISSUE THREAD

**Issue by Nellz91** [lasiadhi/USACE-Bathymetry#142]

**Comment by gmuldoon** [comment]
MCMC real: Code/Inverse_problem/MCMC/MCMC_lasi/MCMC-REAL.mat 

Same as in REAL_plot1_chopped_propSD0_1prSD0_5_totstep1000_kOct9

**Comment by Nellz91** [comment]
You almost killed me with this! Lol
