### ISSUE TITLE
FINISH ALL THE THINGS

### ISSUE THREAD

**Issue by gmuldoon** [lasiadhi/USACE-Bathymetry#152]
SO CLOSE

**Comment by thesser1** [comment]
I don't know why this issue is so hard to close. Good luck.

**Comment by clintseinen** [comment]
ITS THE  FINAL COUNTDOWN

**Comment by dwb1988** [comment]
great

**Comment by Nellz91** [comment]
Almost there! Take us out with a BANG on the presentation Gail and Clint!
