### ISSUE TITLE
Data exploration

### ISSUE THREAD

**Issue by gmuldoon** [lasiadhi/USACE-Bathymetry#2]
Right now:
- loading k and f data from video (argus files) 
- create timeseries for boundary condition point @clintseinen

**Comment by gmuldoon** [comment]
Test bathymetry:

http://chlthredds.erdc.dren.mil/thredds/dodsC/frf/projects/bathyduck/data/FRF-ocean_waves_awac04_201510.nc?waveHs[0:1:644],time[0:1:644],depth[0:1:0],lat,lon

**Comment by gmuldoon** [comment]
@clintseinen 

Example of loading in the "boundary condition" point:

bc.time=ncread('http://chlthredds.erdc.dren.mil/thredds/dodsC/frf/projects/bathyduck/data/FRF-ocean_waves_awac04_201510.nc?waveHs[0:1:644],time[0:1:644],depth[0:1:0],lat,lon','time');
bc.waveHs=ncread('http://chlthredds.erdc.dren.mil/thredds/dodsC/frf/projects/bathyduck/data/FRF-ocean_waves_awac04_201510.nc?waveHs[0:1:644],time[0:1:644],depth[0:1:0],lat,lon','waveHs');
bc.depth=ncread('http://chlthredds.erdc.dren.mil/thredds/dodsC/frf/projects/bathyduck/data/FRF-ocean_waves_awac04_201510.nc?waveHs[0:1:644],time[0:1:644],depth[0:1:0],lat,lon','depth');
bc.lat=ncread('http://chlthredds.erdc.dren.mil/thredds/dodsC/frf/projects/bathyduck/data/FRF-ocean_waves_awac04_201510.nc?waveHs[0:1:644],time[0:1:644],depth[0:1:0],lat,lon','lat');
bc.lon=ncread('http://chlthredds.erdc.dren.mil/thredds/dodsC/frf/projects/bathyduck/data/FRF-ocean_waves_awac04_201510.nc?waveHs[0:1:644],time[0:1:644],depth[0:1:0],lat,lon','lon');

**Comment by thesser1** [comment]
@gmuldoon @clintseinen I forgot to let you know that the true bathymetry is located at http://chlthredds.erdc.dren.mil/thredds/catalog/frf/projects/bathyduck/survey/gridded/catalog.html

**Comment by gmuldoon** [comment]
Found it. Thanks!
