### ISSUE TITLE
Problem loading data from thredds

### ISSUE THREAD

**Issue by gmuldoon** [lasiadhi/USACE-Bathymetry#26]
@clintseinen can you try this on your machine?

I'm suddenly having an issue loading data. Specifically, when loading a time field from a url, I get values ~ 10^261. Values should be ~ 10^9. This code was working properly earlier today.

Example:
filename = 'http://chlthredds.erdc.dren.mil/thredds/dodsC/frf/projects/bathyduck/data/BathyDuck-ocean_bathy_argus_201510.nc';
time = ncread(filename,'time');

**Comment by gmuldoon** [comment]
@thesser1 

The file above was edited today at 20:39:22Z (about 4:20pm our time) and I think maybe it was corrupted in the process. Advice? It's the file for all October data and our source for k...

**Comment by thesser1** [comment]
Oops my bad. I will fix it.

**Comment by thesser1** [comment]
@gmuldoon fixed it.  I tested it and the data looks fine.

**Comment by gmuldoon** [comment]
@thesser1 

Did you test it on my minimal working example, by chance? I'm now getting times that are 10^275.

**Comment by gmuldoon** [comment]
Update: Something is fishy. 

Every time I do

time = ncread(filename,'time');
max(time)

I get a majorly different value (10^-263 to 10^275). This is without updating the filename in between. I'm stumped about what could be causing this. If you have a suggestion for a test, I'd appreciate it.

@thesser1

**Comment by thesser1** [comment]
which code?  I am running get2Dk and it is working just fine.  the
max(time) is returning 1.4463e+09

**Comment by gmuldoon** [comment]
Interesting...I'm running it and it's throwing an error. Maybe it's time to close and reopen that function/Matlab.

**Comment by thesser1** [comment]
Did that fix it or is it still bugging out?  Have you changed the code from
the one in the data branch of the repo?

**Comment by gmuldoon** [comment]
No dice. I had added one line but it was later in the script and I double checked that pulling down the version I pushed earlier doesn't fix it.

I get this error:

```
k = get2Dk()
Error using ncread
Expected count to be positive.

Error in internal.matlab.imagesci.nc/read
(line 562)
                    validateattributes(count,{'numeric'},...

Error in ncread (line 58)
vardata = ncObj.read(varName, varargin{:});

Error in get2Dk (line 54)
    k = ncread(filename,'k',first,last);
```

which I believe stems back to the original MWE of bad times. Trying the MWE on the command line still gives wonky values for both me and Clint.

**Comment by gmuldoon** [comment]
Interim fix:

File now lives at 

http://chlthredds.erdc.dren.mil/thredds/dodsC/frf/projects/bathyduck/BathyDuck-ocean_bathy_argus_201510.nc

get2Dk.m now works properly.
