### ISSUE TITLE
Datum shift for survey elevation?

### ISSUE THREAD

**Issue by clintseinen** [lasiadhi/USACE-Bathymetry#29]
Hey @thesser1 I've pulled the elevation from the transect of interest and I've noticed that this survey is referenced to NAVD88. Do you know where I can find information on shifting the data to be referenced to water level? 

I'm assuming I'll need to shift it before I multiply it by -1 to get the true depth; is this correct?

**Comment by clintseinen** [comment]
For now I'll just flip the data, but I'll add a dumby shift variable and set it to zero.

**Comment by thesser1** [comment]
You could do one of two things.  You can grab a tidal signal for your time period from tides and currents for duck, nc or you can use navd88 as your datum for the initial validation work.

**Comment by clintseinen** [comment]
Okay, for now, I will just use the navd88 for the initial validation work. At a later point I'll look into getting the tide level from duck.
