### ISSUE TITLE
Inverse model

### ISSUE THREAD

**Issue by gmuldoon** [lasiadhi/USACE-Bathymetry#3]

**Comment by lasiadhi** [comment]
Implemented and tested two Matlab functions, i.e. lsqnonneg and lsqnonlin to solve the least squares minimization problem (Inverse problem) using the simulated data. Now I am looking for another existing method to solve the regularized least squares problem in Matlab.

**Comment by lasiadhi** [comment]
Found a Matlab function to solve the Tikhonov regularization with a prior.

**Comment by lasiadhi** [comment]
Implemented the Tikhonov regularization with a prior method and tested with dummy data.
