### ISSUE TITLE
Making plots consistent

### ISSUE THREAD

**Issue by lasiadhi** [lasiadhi/USACE-Bathymetry#75]

**Comment by thesser1** [comment]
What does this mean?

**Comment by lasiadhi** [comment]
At the moment I have three inverse methods. But they have tested under three different sample datasets. I am going to run all three methods under one dataset and put reconstruction plots into the report.

**Comment by lasiadhi** [comment]
I have generated sample data (A and true_h) using random values.

**Comment by lasiadhi** [comment]
Done!
