### ISSUE TITLE
'fsolve' refuses to work again

### ISSUE THREAD

**Issue by dwb1988** [lasiadhi/USACE-Bathymetry#76]
after loaded real data, the 'fsolve' keeps giving us unreasonable values (400+ and jumps to 0 somewhere) for wave number.

need to consider other methods as the bathymetry (the data of depth) does not change a lot...

**Comment by thesser1** [comment]
make your initial guess for k equal to omega/sqrt(g*h)

**Comment by thesser1** [comment]
Did this fix the problem with fsolve?  Lea and I believe the problem is
with the initial guess.

**Comment by dwb1988** [comment]
solved by newton method...
I am trying fsolve

**Comment by dwb1988** [comment]
fsolve works~
tried to plot the dispersion function, seems really well-behavior one... why still stick with initial guess....
