### ISSUE TITLE
Re-add 1D bathy plots.

### ISSUE THREAD

**Issue by clintseinen** [lasiadhi/USACE-Bathymetry#77]
Deal with large amount of .git problems that Clint has been experiencing. He has figured them out. This took a loooong time.

He must re-add the 1d bathy plots and continue writing.

**Comment by clintseinen** [comment]
Update the dam the plot. My brain is exploding. This will be fixed in the morning, for now I will keep writing.....

**Comment by thesser1** [comment]
Maybe some sleep is in order.
